### ISSUE TITLE
make a draft research proposal draft

### ISSUE THREAD

**Issue by Kenkentake** [ridgei/large_scale_ablation#4]
## Summary
make a draft research proposal

## Goal
submit to Kimura-san

## Todo
- [ ] make a draft research proposal by Takemoto
- [ ] review and modify by Okuda-san
- [ ] submit to Kimura-san

## Deadline
07/16

## Parent issue
None

## References
None

## Notes
None

**Comment by Kenkentake** [comment]
made a google document for draft research proposal [here](https://docs.google.com/document/d/1h4af4z21Wv5b-hRNsg0FZ6RFnqcy8jlJeM1FDTqiKgE/edit#heading=h.tvxrqlqb3abr).

**Comment by Kenkentake** [comment]
I will write a first draft by 7/14
